### ISSUE TITLE
TODO: Test case for UUID

### ISSUE THREAD

**Issue by ashegoulding** [ashegoulding/libashe#6]
- [x] 1. Default random engine.
- [x] 2. Random Engine performance.
- [x] 3. fromString() tests for all 5 levels.
- [x] 4. validateRaw()
- [x] 5. merge() operator.
- [x] 6. Random engine collision test.
- [x] 7. Randomisation collision test.

**Comment by ashegoulding** [comment]
1, 2: commit 1ba2c184b0bcb07a47b77d906d1dd7abb1f352b0

**Comment by ashegoulding** [comment]
3, 4, 5, 7: commit 2920db6e5810822206266210db5ca6d996ba7053

**Comment by ashegoulding** [comment]
6: commit 5b4eb2a2ccdfb63de95e6d49084db0f3fd820bb1
